export const CREATE_EXCURSION_REQUEST = 'CREATE_EXCURSION_REQUEST';
export const CREATE_EXCURSION_SUCCESS = 'CREATE_EXCURSION_SUCCESS';
export const CREATE_EXCURSION_FAILURE = 'CREATE_EXCURSION_FAILURE';