export const CREATE_EXCURSION_REQUEST = 'CREATE_EXCURSION_REQUEST';
export const CREATE_EXCURSION_SUCCESS = 'CREATE_EXCURSION_SUCCESS';
export const CREATE_EXCURSION_FAILURE = 'CREATE_EXCURSION_FAILURE';
export const GET_ALL_SERVICES = 'GET_ALL_SERVICES';
export const DELETE_SERVICE = 'DELETE_SERVICE';
export const TOGGLE_SERVICE_STATUS_SUCCESS = 'TOGGLE_SERVICE_STATUS_SUCCESS';