//excursiones
export const CREATE_EXCURSION_REQUEST = "CREATE_EXCURSION_REQUEST";
export const CREATE_EXCURSION_SUCCESS = "CREATE_EXCURSION_SUCCESS";
export const CREATE_EXCURSION_FAILURE = "CREATE_EXCURSION_FAILURE";
export const GET_ALL_SERVICES = "GET_ALL_SERVICES";

// bookings por servicio
export const GET_BOOKINGS_BY_SERVICE_REQUEST =
  "GET_BOOKINGS_BY_SERVICE_REQUEST";
export const GET_BOOKINGS_BY_SERVICE_SUCCESS =
  "GET_BOOKINGS_BY_SERVICE_SUCCESS";
export const GET_BOOKINGS_BY_SERVICE_FAILURE =
  "GET_BOOKINGS_BY_SERVICE_FAILURE";

// servicios
export const DELETE_SERVICE = "DELETE_SERVICE";
export const TOGGLE_SERVICE_STATUS_SUCCESS = "TOGGLE_SERVICE_STATUS_SUCCESS";

//types user
//todos los usuarios
export const GET_USERS_REQUEST = "GET_USERS_REQUEST";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAILURE = "GET_USERS_FAILURE";

//toggle user
export const TOGGLE_USER_STATUS_SUCCESS = "TOGGLE_USER_STATUS_SUCCESS";
export const TOGGLE_USER_STATUS_FAILURE = "TOGGLE_USER_STATUS_FAILURE";
export const TOGGLE_USER_STATUS_REQUEST = "TOGGLE_USER_STATUS_REQUEST";

//delete user
export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAILURE = "DELETE_USER_FAILURE";

//usuarios por ID
export const GET_USER_DETAILS_REQUEST = "GET_USER_DETAILS_REQUEST";
export const GET_USER_DETAILS_SUCCESS = "GET_USER_DETAILS_SUCCESS";
export const GET_USER_DETAILS_FAILURE = "GET_USER_DETAILS_FAILURE";
export const SET_USER_ID = "SET_USER_ID";

//usuarios por name
export const GET_USER_BY_NAME_REQUEST = "GET_USER_BY_NAME_REQUEST";
export const GET_USER_BY_NAME_SUCCESS = "GET_USER_BY_NAME_SUCCESS";
export const GET_USER_BY_NAME_FAILURE = "GET_USER_BY_NAME_FAILURE";

//usuarios por DNI
export const GET_USER_BY_DNI_REQUEST = "GET_USER_BY_DNI_REQUEST";
export const GET_USER_BY_DNI_SUCCESS = "GET_USER_BY_DNI_SUCCESS";
export const GET_USER_BY_DNI_FAILURE = "GET_USER_BY_DNI_FAILURE";

//MODIFICAR USUARIO
export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAILURE = "UPDATE_USER_FAILURE";

//ordenes de servicio
export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAILURE = "CREATE_ORDER_FAILURE";
export const RESET_ORDER = "RESET_ORDER";
export const GET_ALL_ORDERS = "GET_ALL_ORDERS";
export const GET_ALL_ORDERS_REQUEST = "GET_ALL_ORDERS_REQUEST";
export const GET_ALL_ORDERS_ERROR = "GET_ALL_ORDERS_ERROR";

// ordenes de servicio por user
export const GET_ORDERS_BY_USER_REQUEST = "GET_ORDERS_BY_USER_REQUEST";
export const GET_ORDERS_BY_USER_SUCCESS = "GET_ORDERS_BY_USER_SUCCESS";
export const GET_ORDERS_BY_USER_FAILURE = "GET_ORDERS_BY_USER_FAILURE";

//bookings
export const GET_ALL_BOOKINGS = "GET_ALL_BOOKINGS";
export const GET_ALL_BOOKINGS_REQUEST = "GET_ALL_BOOKINGS_REQUEST";
export const GET_ALL_BOOKINGS_ERROR = "GET_ALL_BOOKINGS_ERROR";
